

services:
  mariadb:
    image: mariadb:11.3
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zwitscher
      MYSQL_USER: zwitscher_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_USER: zwitscher_user
      DB_PASSWORD: secret
      DB_NAME: zwitscher
    depends_on:
      - mariadb

volumes:
  mariadb_data:
