version: '3.8'

services:
  db:
    image: mariadb:11.3
    container_name: zwitscher-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zwitscher
      MYSQL_USER: zwitscher_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "zwitscher_user", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend1:
    build:
      context: ./backend
    restart: always
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: zwitscher_user
      DB_PASSWORD: secret
      DB_NAME: zwitscher
      JWT_SECRET: zwitschernistcool
      JWT_EXPIRES_IN: 5h

  backend2:
    build:
      context: ./backend
    restart: always
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: zwitscher_user
      DB_PASSWORD: secret
      DB_NAME: zwitscher
      JWT_SECRET: zwitschernistcool
      JWT_EXPIRES_IN: 5h

  nginx:
    image: nginx:alpine
    container_name: zwitscher-lb
    ports:
      - "3000:80"
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro

  frontend:
    build:
      context: ./frontend
    container_name: zwitscher-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - nginx

volumes:
  db_data:
